version: '3.8'

volumes:
  pgdata:

services:
  db:
    container_name: apimobiliaria
    image: postgres:latest
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
  app:
    build: ./
    image: app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 3001:3001
