version: '3.8'

volumes:
  pgdata:

services:
  db:
    container_name: apimobiliaria
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
  app:
    build: ./
    image: app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 3001:3001
