version: '3.8'
volumes:
  pgdata:
services:
  db:
    container_name: apimobiliaria
    image: postgres
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      # - $HOME/Desktop/apimobiliaria/app/infile:/infile
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
  app:
    build: ./
    image: app
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 3001:3001

networks:
  postgres:
    driver: bridge
